# Generated by Django 4.2.1 on 2023-05-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='miniatura',
            field=models.ImageField(null=True, upload_to='videos/%y'),
        ),
    ]
